### ISSUE TITLE
[BUG] No Login Possible behind nginx reverse proxy with active access control 

### ISSUE THREAD

**Issue by funky123** [jordan-dalby/ByteStash#77]
**Describe the bug**
After activating the directory protection of the reverse proxy manager Nginx, I am asked for the password of the directory protection and then I get to the login of ByteStash itself, if I log in there, it asks again for the directory protection, but does not accept it

**To Reproduce**
Install ByteStash
Order HTTPS with Lets Encrypt
Activate Activate Access Control

**Expected behavior**
Login should work

**Screenshots**
![image](https://github.com/user-attachments/assets/a8e14c04-9297-4c2b-be55-f5276c72f754)
![image](https://github.com/user-attachments/assets/f33457e9-2b09-475c-9aa6-2f9b1cb0fb48)

**Platform**
docker compose

**Comment by vlavrynovych** [comment]
For those how is struggly with this problem at the moment there is an alternative solution with a Cloudflare Tunnels.
The Cloudflare is free. It requires:
- to have a Docker in your network instead of nginx proxy manager
- to have a domain (buy or free)
- chage nameservers of your domain to Cloudflare

Read more about how to setup Cloudflare Tunnels [here](https://lavr.site/en-how-to-use-cloudflare-zero-trust-tunnels-to-expose-private-self-hosted-services-to-the-internet/)

**Comment by jordan-dalby** [comment]
@funky123 
Can you retry this with bytestash-dev:pr-111 I made some changes to http/https configuration and am curious if that fixed it

**Comment by funky123** [comment]
I will, give me some time I have a newborn at home :) thank God !

Diese E-Mail wurde von meinem Smartphone aus gesendet und beinhaltet daher nur das Nötigste.

Mit freundlichen Grüßen
Micha Welter
________________________________

**Comment by jordan-dalby** [comment]
@funky123 No worries! I just did a bit of testing and it seems like it's still broken, I will try to fix it for v1.5.2 :)

**Comment by funky123** [comment]
Thanks for your time and work! So I don't have to check it right now?

Diese E-Mail wurde von meinem Smartphone aus gesendet und beinhaltet daher nur das Nötigste.

Mit freundlichen Grüßen
Micha Welter
________________________________

**Comment by jordan-dalby** [comment]
@funky123 
Not yet, I'll update you when I have a fix :)

**Comment by jordan-dalby** [comment]
@funky123 
Fixed! Please give it another try, bytestash-dev:pr-113

**Comment by funky123** [comment]
with stable still not working, right?

ByteStash v1.5.4 with access lists

**Comment by funky123** [comment]
> [@funky123](https://github.com/funky123) Fixed! Please give it another try, bytestash-dev:pr-113

did you fix it?

**Comment by jordan-dalby** [comment]
@funky123 
It's working on my side. Do you have any special configuration options?

**Comment by funky123** [comment]
> [@funky123](https://github.com/funky123) It's working on my side. Do you have any special configuration options?

my bad, i set up my npm incorretly with acl, wasnt a bytestash issue, srorry!

But i had some other issu, could log in with that user from config.yml which i set, maybee beq i used simple user and pass below 8 digits?

That would be great if thats the case if there is a little hint that pw has to be 8 digits :)
